SHOW DATABASES;
USE ccm;
SHOW TABLES;
DESCRIBE cliente;
SELECT * FROM cliente;
SELECT * FROM tarjeta;

/* PROCEDIMIENTOS ALMACENADOS */
/*INGRESAR VALORES EN LA TABLA DE CLIENTE CUANDO AÚN NO REGISTRA TARJETA*/

/*INGRESAR VALORES EN LA TABLA DE CLIENTE CUANDO YA REGISTRÓ TARJETA*/

/*INGRESAR EL VALOR DE LA TARJETA A LA TABLA DE CLIENTE*/

/*INGRESAR EL VALOR DE ID DEL PEDIDO A LA TABLA DE CLIENTE*/

/*INGRESAR VALORES EN LA TABLA DE TARJETA*/

/*INGRESAR VALORES EN LA TABLA DE DIRECCION*/

/*INGRESAR VALORES EN LA TABLA DE */

/*INGRESAR VALORES EN LA TABLA DE ZAPATO*/